resource.settings:
  delimiter: '-'
  path: 'public://csv/FPNTC_Resources_reformatted.csv'
  id: 1
  #number of columns that will be concatinated
  destinations:
    field_intended_audience:
      - intended_audience
    field_resource_type: {}
    field_topics:
      - topics
    field_purpose: {}